<?php

namespace Database\Seeders;

use App\Models\Budget;
use App\Models\BudgetItem;
use Illuminate\Database\Seeder;

class BudgetItemSeeder extends Seeder
{
    public function run(): void
    {
        $budgets = Budget::all();

        if ($budgets->isEmpty()) {
            $this->command->warn('Please run BudgetSeeder first!');
            return;
        }

        // Get the first active budget (RAB-2024-001)
        $activeBudget = $budgets->where('budget_code', 'RAB-2024-001')->first();

        if (!$activeBudget) {
            $this->command->warn('No active budget found!');
            return;
        }

        // Level 1: Main Categories
        $categories = [
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => null,
                'code' => 'RAB-001',
                'name' => 'Biaya Operasional',
                'description' => 'Biaya operasional harian organisasi',
                'category' => 'operational',
                'level' => 1,
                'order' => 1,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 60000000.00,
                'subtotal' => 60000000.00,
                'planned_amount' => 60000000.00,
                'approved_amount' => 58000000.00,
                'allocated_amount' => 45000000.00,
                'spent_amount' => 28000000.00,
                'remaining_amount' => 17000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Mencakup semua kebutuhan operasional bulanan',
                'justification' => 'Diperlukan untuk kelancaran operasional sehari-hari',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => null,
                'code' => 'RAB-002',
                'name' => 'Biaya Event',
                'description' => 'Biaya untuk penyelenggaraan berbagai event',
                'category' => 'event',
                'level' => 1,
                'order' => 2,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 120000000.00,
                'subtotal' => 120000000.00,
                'planned_amount' => 120000000.00,
                'approved_amount' => 115000000.00,
                'allocated_amount' => 90000000.00,
                'spent_amount' => 42000000.00,
                'remaining_amount' => 48000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Event utama organisasi sepanjang tahun',
                'justification' => 'Event merupakan program inti organisasi',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => null,
                'code' => 'RAB-003',
                'name' => 'Peralatan & Perlengkapan',
                'description' => 'Pengadaan peralatan dan perlengkapan',
                'category' => 'equipment',
                'level' => 1,
                'order' => 3,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 40000000.00,
                'subtotal' => 40000000.00,
                'planned_amount' => 40000000.00,
                'approved_amount' => 38000000.00,
                'allocated_amount' => 28000000.00,
                'spent_amount' => 12000000.00,
                'remaining_amount' => 16000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Untuk upgrade dan pembelian baru',
                'justification' => 'Peralatan lama sudah tidak memadai',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => null,
                'code' => 'RAB-004',
                'name' => 'Marketing & Promosi',
                'description' => 'Biaya marketing dan promosi kegiatan',
                'category' => 'marketing',
                'level' => 1,
                'order' => 4,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 30000000.00,
                'subtotal' => 30000000.00,
                'planned_amount' => 30000000.00,
                'approved_amount' => 29000000.00,
                'allocated_amount' => 17000000.00,
                'spent_amount' => 3000000.00,
                'remaining_amount' => 14000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Untuk publikasi dan branding',
                'justification' => 'Meningkatkan awareness organisasi',
            ],
        ];

        $categoryIds = [];
        foreach ($categories as $category) {
            $item = BudgetItem::create($category);
            $categoryIds[$category['code']] = $item->id;
        }

        // Level 2: Sub-categories and Main Items
        $mainItems = [
            // Operational Items
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-001'],
                'code' => 'RAB-001.1',
                'name' => 'Sewa Kantor',
                'description' => 'Biaya sewa kantor bulanan',
                'category' => 'operational',
                'level' => 2,
                'order' => 1,
                'quantity' => 12,
                'unit' => 'bulan',
                'unit_price' => 5000000.00,
                'subtotal' => 60000000.00,
                'planned_amount' => 60000000.00,
                'approved_amount' => 60000000.00,
                'allocated_amount' => 50000000.00,
                'spent_amount' => 30000000.00,
                'remaining_amount' => 20000000.00,
                'priority' => 'critical',
                'is_mandatory' => true,
                'notes' => 'Sewa gedung kantor per bulan',
                'justification' => 'Kebutuhan tetap bulanan',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-001'],
                'code' => 'RAB-001.2',
                'name' => 'Utilitas (Listrik, Air, Internet)',
                'description' => 'Biaya utilitas bulanan',
                'category' => 'operational',
                'level' => 2,
                'order' => 2,
                'quantity' => 12,
                'unit' => 'bulan',
                'unit_price' => 3000000.00,
                'subtotal' => 36000000.00,
                'planned_amount' => 36000000.00,
                'approved_amount' => 35000000.00,
                'allocated_amount' => 28000000.00,
                'spent_amount' => 18000000.00,
                'remaining_amount' => 10000000.00,
                'priority' => 'critical',
                'is_mandatory' => true,
                'notes' => 'Listrik, air, internet, dan telepon',
                'justification' => 'Kebutuhan operasional dasar',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-001'],
                'code' => 'RAB-001.3',
                'name' => 'ATK & Supplies',
                'description' => 'Alat tulis kantor dan perlengkapan',
                'category' => 'operational',
                'level' => 2,
                'order' => 3,
                'quantity' => 12,
                'unit' => 'bulan',
                'unit_price' => 2000000.00,
                'subtotal' => 24000000.00,
                'planned_amount' => 24000000.00,
                'approved_amount' => 22000000.00,
                'allocated_amount' => 15000000.00,
                'spent_amount' => 8000000.00,
                'remaining_amount' => 7000000.00,
                'priority' => 'medium',
                'is_mandatory' => true,
                'notes' => 'Kebutuhan ATK bulanan',
                'justification' => 'Untuk kelancaran administrasi',
            ],

            // Event Items
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-002'],
                'code' => 'RAB-002.1',
                'name' => 'Seminar Nasional',
                'description' => 'Penyelenggaraan seminar nasional tahunan',
                'category' => 'event',
                'level' => 2,
                'order' => 1,
                'quantity' => 1,
                'unit' => 'event',
                'unit_price' => 60000000.00,
                'subtotal' => 60000000.00,
                'planned_amount' => 60000000.00,
                'approved_amount' => 58000000.00,
                'allocated_amount' => 50000000.00,
                'spent_amount' => 30000000.00,
                'remaining_amount' => 20000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Event flagship organisasi',
                'justification' => 'Program unggulan tahunan',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-002'],
                'code' => 'RAB-002.2',
                'name' => 'Workshop Series',
                'description' => 'Workshop bulanan untuk anggota',
                'category' => 'event',
                'level' => 2,
                'order' => 2,
                'quantity' => 10,
                'unit' => 'workshop',
                'unit_price' => 3500000.00,
                'subtotal' => 35000000.00,
                'planned_amount' => 35000000.00,
                'approved_amount' => 34000000.00,
                'allocated_amount' => 25000000.00,
                'spent_amount' => 10000000.00,
                'remaining_amount' => 15000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Workshop pengembangan skill anggota',
                'justification' => 'Peningkatan kapasitas anggota',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-002'],
                'code' => 'RAB-002.3',
                'name' => 'Gathering & Team Building',
                'description' => 'Kegiatan gathering dan team building',
                'category' => 'event',
                'level' => 2,
                'order' => 3,
                'quantity' => 2,
                'unit' => 'event',
                'unit_price' => 12500000.00,
                'subtotal' => 25000000.00,
                'planned_amount' => 25000000.00,
                'approved_amount' => 23000000.00,
                'allocated_amount' => 15000000.00,
                'spent_amount' => 2000000.00,
                'remaining_amount' => 13000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Untuk mempererat hubungan antar anggota',
                'justification' => 'Meningkatkan kekompakan tim',
            ],

            // Equipment Items
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-003'],
                'code' => 'RAB-003.1',
                'name' => 'Komputer & Laptop',
                'description' => 'Pengadaan komputer dan laptop baru',
                'category' => 'equipment',
                'level' => 2,
                'order' => 1,
                'quantity' => 5,
                'unit' => 'unit',
                'unit_price' => 4000000.00,
                'subtotal' => 20000000.00,
                'planned_amount' => 20000000.00,
                'approved_amount' => 19000000.00,
                'allocated_amount' => 15000000.00,
                'spent_amount' => 8000000.00,
                'remaining_amount' => 7000000.00,
                'priority' => 'high',
                'is_mandatory' => false,
                'notes' => 'Untuk staff baru dan replacement',
                'justification' => 'Peralatan lama sudah tidak support',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-003'],
                'code' => 'RAB-003.2',
                'name' => 'Proyektor & Sound System',
                'description' => 'Proyektor dan sound system untuk event',
                'category' => 'equipment',
                'level' => 2,
                'order' => 2,
                'quantity' => 2,
                'unit' => 'set',
                'unit_price' => 7500000.00,
                'subtotal' => 15000000.00,
                'planned_amount' => 15000000.00,
                'approved_amount' => 14000000.00,
                'allocated_amount' => 10000000.00,
                'spent_amount' => 3000000.00,
                'remaining_amount' => 7000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Untuk kebutuhan event',
                'justification' => 'Mengurangi biaya sewa',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-003'],
                'code' => 'RAB-003.3',
                'name' => 'Furniture Kantor',
                'description' => 'Meja, kursi, dan lemari kantor',
                'category' => 'equipment',
                'level' => 2,
                'order' => 3,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 5000000.00,
                'subtotal' => 5000000.00,
                'planned_amount' => 5000000.00,
                'approved_amount' => 5000000.00,
                'allocated_amount' => 3000000.00,
                'spent_amount' => 1000000.00,
                'remaining_amount' => 2000000.00,
                'priority' => 'low',
                'is_mandatory' => false,
                'notes' => 'Penambahan furniture untuk ruang baru',
                'justification' => 'Perluasan area kerja',
            ],

            // Marketing Items
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-004'],
                'code' => 'RAB-004.1',
                'name' => 'Social Media Marketing',
                'description' => 'Konten dan iklan social media',
                'category' => 'marketing',
                'level' => 2,
                'order' => 1,
                'quantity' => 12,
                'unit' => 'bulan',
                'unit_price' => 1500000.00,
                'subtotal' => 18000000.00,
                'planned_amount' => 18000000.00,
                'approved_amount' => 17000000.00,
                'allocated_amount' => 10000000.00,
                'spent_amount' => 2000000.00,
                'remaining_amount' => 8000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Instagram, Twitter, dan Facebook ads',
                'justification' => 'Meningkatkan brand awareness',
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $categoryIds['RAB-004'],
                'code' => 'RAB-004.2',
                'name' => 'Merchandise & Branding',
                'description' => 'Pembuatan merchandise dan material branding',
                'category' => 'marketing',
                'level' => 2,
                'order' => 2,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 12000000.00,
                'subtotal' => 12000000.00,
                'planned_amount' => 12000000.00,
                'approved_amount' => 12000000.00,
                'allocated_amount' => 7000000.00,
                'spent_amount' => 1000000.00,
                'remaining_amount' => 6000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'T-shirt, sticker, banner, dll',
                'justification' => 'Untuk kegiatan promosi',
            ],
        ];

        $mainItemIds = [];
        foreach ($mainItems as $item) {
            $created = BudgetItem::create($item);
            $mainItemIds[$item['code']] = $created->id;
        }

        // Level 3: Detail Items (Sub-items of main items)
        $detailItems = [
            // Seminar Nasional Detail
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.1'],
                'code' => 'RAB-002.1.1',
                'name' => 'Venue & Catering',
                'description' => 'Sewa venue dan konsumsi peserta',
                'category' => 'event',
                'level' => 3,
                'order' => 1,
                'quantity' => 200,
                'unit' => 'pax',
                'unit_price' => 150000.00,
                'subtotal' => 30000000.00,
                'planned_amount' => 30000000.00,
                'approved_amount' => 29000000.00,
                'allocated_amount' => 25000000.00,
                'spent_amount' => 15000000.00,
                'remaining_amount' => 10000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Hotel bintang 4 dengan paket meeting',
                'justification' => null,
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.1'],
                'code' => 'RAB-002.1.2',
                'name' => 'Narasumber & Moderator',
                'description' => 'Honorarium narasumber dan moderator',
                'category' => 'personnel',
                'level' => 3,
                'order' => 2,
                'quantity' => 5,
                'unit' => 'orang',
                'unit_price' => 3000000.00,
                'subtotal' => 15000000.00,
                'planned_amount' => 15000000.00,
                'approved_amount' => 14500000.00,
                'allocated_amount' => 12000000.00,
                'spent_amount' => 8000000.00,
                'remaining_amount' => 4000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => '3 narasumber utama dan 2 moderator',
                'justification' => null,
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.1'],
                'code' => 'RAB-002.1.3',
                'name' => 'Dokumentasi & Publikasi',
                'description' => 'Tim dokumentasi dan publikasi event',
                'category' => 'marketing',
                'level' => 3,
                'order' => 3,
                'quantity' => 1,
                'unit' => 'paket',
                'unit_price' => 5000000.00,
                'subtotal' => 5000000.00,
                'planned_amount' => 5000000.00,
                'approved_amount' => 4500000.00,
                'allocated_amount' => 3000000.00,
                'spent_amount' => 2000000.00,
                'remaining_amount' => 1000000.00,
                'priority' => 'medium',
                'is_mandatory' => false,
                'notes' => 'Fotografer, videografer, dan konten creator',
                'justification' => null,
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.1'],
                'code' => 'RAB-002.1.4',
                'name' => 'Material Event',
                'description' => 'Sertifikat, goodie bag, dan material lain',
                'category' => 'logistics',
                'level' => 3,
                'order' => 4,
                'quantity' => 200,
                'unit' => 'set',
                'unit_price' => 50000.00,
                'subtotal' => 10000000.00,
                'planned_amount' => 10000000.00,
                'approved_amount' => 10000000.00,
                'allocated_amount' => 10000000.00,
                'spent_amount' => 5000000.00,
                'remaining_amount' => 5000000.00,
                'priority' => 'medium',
                'is_mandatory' => true,
                'notes' => 'Untuk semua peserta',
                'justification' => null,
            ],

            // Workshop Detail
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.2'],
                'code' => 'RAB-002.2.1',
                'name' => 'Trainer & Fasilitator',
                'description' => 'Honorarium trainer workshop',
                'category' => 'personnel',
                'level' => 3,
                'order' => 1,
                'quantity' => 10,
                'unit' => 'sesi',
                'unit_price' => 2000000.00,
                'subtotal' => 20000000.00,
                'planned_amount' => 20000000.00,
                'approved_amount' => 19000000.00,
                'allocated_amount' => 15000000.00,
                'spent_amount' => 6000000.00,
                'remaining_amount' => 9000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Trainer professional sesuai tema',
                'justification' => null,
            ],
            [
                'budget_id' => $activeBudget->id,
                'parent_id' => $mainItemIds['RAB-002.2'],
                'code' => 'RAB-002.2.2',
                'name' => 'Venue & Konsumsi',
                'description' => 'Tempat dan konsumsi workshop',
                'category' => 'event',
                'level' => 3,
                'order' => 2,
                'quantity' => 10,
                'unit' => 'sesi',
                'unit_price' => 1500000.00,
                'subtotal' => 15000000.00,
                'planned_amount' => 15000000.00,
                'approved_amount' => 15000000.00,
                'allocated_amount' => 10000000.00,
                'spent_amount' => 4000000.00,
                'remaining_amount' => 6000000.00,
                'priority' => 'high',
                'is_mandatory' => true,
                'notes' => 'Ruangan dan snack untuk 30-40 peserta',
                'justification' => null,
            ],
        ];

        foreach ($detailItems as $item) {
            BudgetItem::create($item);
        }

        $totalItems = count($categories) + count($mainItems) + count($detailItems);
        $this->command->info('✅ Budget Item seeder completed! Created ' . $totalItems . ' budget items with hierarchy.');
    }
}
